


USE [C:\GAADB\GAA_GAMES.MDF]
BEGIN TRY
BEGIN TRAN;
INSERT GAMES
VALUES(25, 'Round 2 Connacht Semi-Final', 'Football', 'Hyde Park, Roscommon', '06/20/2014', '14:30');
INSERT Ticket_Details VALUES(15, 'Sligo', 'Roscommon', '07:30', '11:15', 25, 4, 100);
COMMIT TRAN;
END TRY
BEGIN CATCH
ROLLBACK TRAN;
END CATCH;

USE [C:\CURRENCYDB\CURRENCY_RATES.MDF]
BEGIN TRY
BEGIN TRAN;
INSERT RATES
VALUES(26, 'YEN to EUR', 0.0072, 4, 5);
INSERT Currency_From VALUES(5, '¥YEN');
COMMIT TRAN;
END TRY
BEGIN CATCH
ROLLBACK TRAN;
END CATCH;

